name: Publish to npm

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/npm-publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      # Install all dependencies
      - name: Install dependencies
        run: npm install
      
      # Build the package
      - name: Build
        run: npm run build
      
      # Verify build output
      - name: Verify build
        run: |
          echo "Checking build output..."
          if [ ! -f "dist/sdk.js" ]; then
            echo "Error: Build failed - sdk.js missing"
            exit 1
          fi
          if [ ! -f "dist/sdk.d.ts" ]; then
            echo "Error: Build failed - sdk.d.ts missing"
            exit 1
          fi
          if [ ! -f "dist/cli.js" ]; then
            echo "Error: Build failed - cli.js missing"
            exit 1
          fi
          echo "Checking SDK files..."
          if [ ! -f "dist/sdk/index.js" ]; then
            echo "Error: SDK files not copied correctly - index.js missing"
            exit 1
          fi
          if [ ! -f "dist/sdk/index.d.ts" ]; then
            echo "Error: SDK files not copied correctly - index.d.ts missing"
            exit 1
          fi
      
      # Make the CLI executable
      - name: Make CLI executable
        run: chmod +x dist/cli.js

      - name: Move readme.md
        run: cp README.md dist/README.md
      
      # Publish
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 